name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Ash-Studio
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          config_display: large
          
          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_stars: yes
          plugin_topics: yes
          plugin_people: yes
          plugin_followup: yes

          filename: github-metrics.svg
          markdown: yes
