# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Allow manual runs and trigger on push to master/main
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # User & Template
          user: Ash-Studio
          template: classic

          # Base sections
          base: header, activity, community, repositories
          config_display: large
          config_timezone: Asia/Kolkata  # Corrected timezone format

          # Achievements (disabled)
          plugin_achievements: false
          plugin_achievements_display: detailed
          plugin_achievements_secrets: false
          plugin_achievements_threshold: C

          # Skyline (disabled)
          plugin_skyline: no
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_year: current-year

          # Wakatime (disabled)
          plugin_wakatime: false
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current

          # Calendar and Lines
          plugin_isocalendar: yes
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
