name: GitHub Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Required
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ash-Studio

          # File output
          filename: github-metrics.svg

          # Base sections
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0 # Show all
          
          plugin_languages: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_isocalendar: yes
