name: Metrics
on:
  schedule: [{ cron: "0 0 * * 0" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ash-Studio
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_stars: yes
          plugin_followup: yes
          plugin_lines: yes
