name: Metrics
on:
  schedule: [{ cron: "0 0 * * 0" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ash-Studio
          template: classic
          base: header, repositories, activity, community, metadata
          config_timezone: Asia/Kolkata

          plugin_lines: yes
          plugin_traffic: yes
          plugin_stars: yes
          plugin_repositories: yes
          plugin_followup: yes
          plugin_reactions: yes
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_notable_repositories: 3
          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_discussions: yes
          plugin_discussions_categories_limit: 5
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 400
